### ISSUE TITLE
DeepL recipe does not pick up version 4.x

### ISSUE THREAD

**Issue by peterkelm** [autopkg/andredb90-recipes#4]
The download URL for DeepL version 4.x for macOS > 11 has changed to:

https://www.deepl.com/macos/download/bigsur/DeepL.dmg

**Comment by andredb90** [comment]
Hi

I'm sorry for the late response. I didn't notice the raised issue until now.


The URL has been updated and it's now pulling the latest version as intended. - Thank you very much!
