### ISSUE TITLE
Nextcloud recipe pulling down 3.82, not latest 3.9.4

### ISSUE THREAD

**Issue by markkenny** [autopkg/andredb90-recipes#5]
Is it because there are no longer installer PKGs in the releases? Only source code.

Website publishes a DL link.. https://github.com/nextcloud-releases/desktop/releases/latest/download/Nextcloud-3.9.4.pkg

Thanks

**Comment by markkenny** [comment]
I see it myself now, the git repo is now nextcloud-releases/desktop and nextcloud/desktop only goes back to 3.8.2

**Comment by andredb90** [comment]
My apologies for not responding and thank you for brining it up! I obviously need to change my notification settings here, as I keep missing them.

Anyways, the issue has been addressed a few weeks ago. I hope everything's working as expected now.
