### ISSUE TITLE
Wrong ProtonVPN version?

### ISSUE THREAD

**Issue by jelockwood** [autopkg/andredb90-recipes#8]
@andredb90 
I have had a look at your ProtonVPN download recipe and it seems to use a URL that is intended to always reflect the latest version by using a generic URL/filename - an approach used by many software authors.

As I suspect you are aware, if you visit their download page there are also some other download URLs which provide _specific_ download links for various macOS versions. Based on these _specific_ URLs the latest version is 4.8.0. However the 'generic' URL only downloads version 4.2.2.

I would say this actually reflects an error on the part of Proton in that they have apparently not kept the generic URL up-to-date or pointing always to the actual latest version and that this is not strictly speaking an error in your recipe. However it maybe you need to consider modifying your recipe to somehow otherwise determine the latest version to download. One approach would be to provide a setting in your recipe to specifically download e.g. the Monterey, Ventura or Big Sur choices.

Note: Monterey and Ventura both link to the same 4.8.0 release and no Sonoma or Sequoia specific options are listed and in my opinion this likely means they use the same 4.8.0 release. (Again arguably Proton have not kept their webpage up-to-date by listing Sonoma and Sequoia.)

However further searching shows Proton seem to have a GitHub repo which contains ProtonVPN releases and this looks like it will be simpler to deal with in that the latest macOS release on this repo is 4.8.0. There is a possibility that a slight complexity here is that the same repo and same list of releases combines options for macOS, TVOS and iOS so care needs to be taken to not get confused by these.

See - https://github.com/ProtonVPN/ios-mac-app/releases

Let me know if you will be making any changes as I have suggested, if not I can write my own version. I intend to add my own munki recipe anyway.

**Comment by jelockwood** [comment]
@andredb90 
Ah! As it happens I have now found that someone else also has an AutoPkg recipe for ProtonVPN and theirs is downloading version 4.8.0 _and_ includes a Munki recipe as well.

See - https://github.com/autopkg/dataJAR-recipes/tree/master/ProtonVPN

It maybe simpler for you to discontinue your recipe.

**Comment by andredb90** [comment]
Hi @jelockwood 

Thanks a lot for point this out and sharing your findings! 

I looked into it and found that dataJAR has already created their own version of the download recipe. 

https://github.com/autopkg/dataJAR-recipes/blob/master/ProtonVPN/ProtonVPN.download.recipe

I'd say there's no point in having multiple variants and after testing the recipe, it does indeed download the latest version (4.8.0). 

I will go ahead and remove my download recipe and change the .pkg and .filewave one to use the new parent.
